services:
  postgres:
    image: postgres:17
    container_name: todo_postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: todo_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: todo_flask

    restart: always

    ports:
      - "5000:5000"

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql://postgres:123456@postgres:5432/todo_db

volumes:
  postgres_data: